controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: true

    rover_base_control:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rover_base_control:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: ["wheels__frontL_link_joint", "wheels__backL_link_joint"]
    right_wheel_names: ["wheels__frontR_link_joint", "wheels__backR_link_joint"]
    wheel_separation: 1.90
    wheel_radius: 0.30
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    base_frame_id: base_footprint
    enable_odom_tf: true
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0

scara_controller:
  ros__parameters:
    joints:
      - _link2_link_joint
      - _link3_link_joint
      - _rot_link4_link_joint
      - _pris_link4_link_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - _pris_link4.001_link_joint
      - _pris_link4.002_link_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity